### ISSUE TITLE
插件编译后，载入出现NPE异常

### ISSUE THREAD

**Issue by SleepyAsh0191** [StageGuard/OsuMapSuggester#2]
编译环境: Openjdk 16

提取文件的时候，在`data\OsuMapSuggester\resources`文件夹中解出来的文件不全

```
2021-10-10 20:36:39 E/OsuMapSuggester: Exception in coroutine Plugin OsuMapSuggester of OsuMapSuggester
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.readAllBytes()" because "inputStream" is null
        at me.stageguard.obms.utils.ExportResourcesKt$exportStaticResourcesToDataFolder$2.invokeSuspend(exportResources.kt:32)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by StageGuard** [comment]
emmm，应该是某个资源忘了export了，我看一下。

**Comment by StageGuard** [comment]
很奇怪，难道是jdk16的问题吗（感觉不太可能

**Comment by SleepyAsh0191** [comment]
我用我自己的电脑还有centos编译都是这个问题

**Comment by SleepyAsh0191** [comment]
> > 要不你用jdk14或者11试试，~顺便问一下你的openjdk16是哪个变体的~
> 
> https://openjdk.java.net/
> 
> openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

我马上去试(

**Comment by StageGuard** [comment]
> > > 要不你用jdk14或者11试试，~顺便问一下你的openjdk16是哪个变体的~
> > 
> > 
> > https://openjdk.java.net/
> > openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
> 
> 我马上去试(

我刚刚推了一个commit，如果还不行的话再build最新的分支启动试试

**Comment by SleepyAsh0191** [comment]
> > > > 要不你用jdk14或者11试试，~顺便问一下你的openjdk16是哪个变体的~
> > > 
> > > 
> > > https://openjdk.java.net/
> > > openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
> > 
> > 
> > 我马上去试(
> 
> 我刚刚推了一个commit，如果还不行的话再build最新的分支启动试试

Runtime: 16
log
```
2021-10-10 21:19:28 I/OsuMapSuggester: Exporting static resources...
2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_a.svg
2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_b.svg
2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_c.svg
2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_d.svg
2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_s.svg
2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_sh.svg
2021-10-10 21:19:28 I/OsuMapSuggester: Successfully exported static resources.
```

等会试试11

**Comment by SleepyAsh0191** [comment]
> > > > > 要不你用jdk14或者11试试，~顺便问一下你的openjdk16是哪个变体的~
> > > > 
> > > > 
> > > > https://openjdk.java.net/
> > > > openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
> > > 
> > > 
> > > 我马上去试(
> > 
> > 
> > 我刚刚推了一个commit，如果还不行的话再build最新的分支启动试试
> 
> Runtime: 16 log
> 
> ```
> 2021-10-10 21:19:28 I/OsuMapSuggester: Exporting static resources...
> 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_a.svg
> 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_b.svg
> 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_c.svg
> 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_d.svg
> 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_s.svg
> 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_sh.svg
> 2021-10-10 21:19:28 I/OsuMapSuggester: Successfully exported static resources.
> ```
> 
> 等会试试11

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

11还是同样的问题，~可能是我编译姿势问题~

**Comment by StageGuard** [comment]
> > > > > > 要不你用jdk14或者11试试，~顺便问一下你的openjdk16是哪个变体的~
> > > > > 
> > > > > 
> > > > > https://openjdk.java.net/
> > > > > openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
> > > > 
> > > > 
> > > > 我马上去试(
> > > 
> > > 
> > > 我刚刚推了一个commit，如果还不行的话再build最新的分支启动试试
> > 
> > 
> > Runtime: 16 log
> > ```
> > 2021-10-10 21:19:28 I/OsuMapSuggester: Exporting static resources...
> > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_a.svg
> > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_b.svg
> > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_c.svg
> > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_d.svg
> > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_s.svg
> > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_sh.svg
> > 2021-10-10 21:19:28 I/OsuMapSuggester: Successfully exported static resources.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 等会试试11
> 
> ```
> openjdk version "11" 2018-09-25
> OpenJDK Runtime Environment 18.9 (build 11+28)
> OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
> ```
> 
> 11还是同样的问题，~可能是我编译姿势问题~
> 
> 尝试手动拖入文件夹中 问题仍然存在
> 
> 正在尝试用11运行(

那你试一下release里build好的？

**Comment by SleepyAsh0191** [comment]
> > > > > > > 要不你用jdk14或者11试试，~顺便问一下你的openjdk16是哪个变体的~
> > > > > > 
> > > > > > 
> > > > > > https://openjdk.java.net/
> > > > > > openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
> > > > > 
> > > > > 
> > > > > 我马上去试(
> > > > 
> > > > 
> > > > 我刚刚推了一个commit，如果还不行的话再build最新的分支启动试试
> > > 
> > > 
> > > Runtime: 16 log
> > > ```
> > > 2021-10-10 21:19:28 I/OsuMapSuggester: Exporting static resources...
> > > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_a.svg
> > > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_b.svg
> > > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_c.svg
> > > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_d.svg
> > > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_s.svg
> > > 2021-10-10 21:19:28 W/OsuMapSuggester: Resource not found: /svg/grade_sh.svg
> > > 2021-10-10 21:19:28 I/OsuMapSuggester: Successfully exported static resources.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 等会试试11
> > 
> > 
> > ```
> > openjdk version "11" 2018-09-25
> > OpenJDK Runtime Environment 18.9 (build 11+28)
> > OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 11还是同样的问题，~可能是我编译姿势问题~
> > 尝试手动拖入文件夹中 问题仍然存在
> > 正在尝试用11运行(
> 
> 那你试一下release里build好的？

载入没问题
