### ISSUE TITLE
关于插件手动编译后运行报错的一点建议

### ISSUE THREAD

**Issue by li14300** [StageGuard/OsuMapSuggester#7]
今天在Debian编译后运行也出现了错误，和 #2 一样的错误，资源没有加载
![Snipaste_2021-12-13_15-55-15](https://user-images.githubusercontent.com/47286109/145775546-0d651228-5a62-4f91-a1fc-2d314aa7c835.jpg)
去看了一下库发现了问题，资源文件的大小写不对，Linux对大小写敏感，造成编译时没有打包进去。
拉下来之后，去改了一下资源的大小写，编译运行成功
建议修改/main/src/main/resources/svg内的文件名

**Comment by StageGuard** [comment]
![image](https://user-images.githubusercontent.com/45701251/145782649-815bbb5f-c1d4-47b4-b3c8-8873d4ee4a7b.png)
是小写的啊...

**Comment by li14300** [comment]
> ![image](https://user-images.githubusercontent.com/45701251/145782649-815bbb5f-c1d4-47b4-b3c8-8873d4ee4a7b.png) 在我本地确实是小写的，不知道为什么push上来变成大写的了

😂

**Comment by StageGuard** [comment]
close via https://github.com/StageGuard/OsuMapSuggester/commit/b589848e0a71c28bfecd539682b78bcba46131f0
